# Generated by Django 3.1.3 on 2020-11-21 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('tag', models.CharField(max_length=15, unique=True, verbose_name='RFID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=15, unique=True, verbose_name='RFID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('time_in', models.DateTimeField(auto_now_add=True, verbose_name='Time-in')),
                ('time_out', models.DateTimeField(blank=True, null=True, verbose_name='Time-out')),
                ('student_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfid.student', verbose_name='Student RFID')),
                ('watch_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfid.watch', verbose_name='Watch RFID')),
            ],
        ),
    ]
