# Generated by Django 3.1.3 on 2020-11-22 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0003_auto_20201122_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student_tag',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='rfid.student', verbose_name='Student RFID'),
        ),
    ]
