# Generated by Django 3.1.3 on 2020-11-22 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0005_auto_20201122_2052'),
    ]

    operations = [
    ]
